### ISSUE TITLE
blog页面貌似有bug

### ISSUE THREAD

**Issue by Kronlal** [zhonger/jekyll-theme-H2O-ac#13]
只会显示置顶的文章，无法显示其余文章，且无分页功能。
就像我搭建的这个一样：
https://kronlal.github.io/blog/index.html

**Comment by zhonger** [comment]
@Kronlal 现在你指向的网页无法访问，是否有截图可以展示一下？

**Comment by zhonger** [comment]
不知道你指的是不是 [Kronlal/Kronlal.github.ioo](https://github.com/Kronlal/Kronlal.github.ioo/tree/master) 项目，我下载了你修改后的代码，并在本地分别尝试了 `_config.yml` 和 `_config_production.yml` 两种配置，blog 页面运行效果及配置中相关代码部分如下所示：

### _config.yml

```yaml
pagination:
  enabled: true
  per_page: 10
```

![image](https://github.com/zhonger/jekyll-theme-H2O-ac/assets/12064158/e4d7f95f-43b2-40ad-bb24-0c7eb167e2bd)


### _config_production.yml

```yaml
pagination:
  enabled: true
  per_page: 1
```

![image](https://github.com/zhonger/jekyll-theme-H2O-ac/assets/12064158/0379249c-8281-456d-b025-2a9a7e2eb06b)

看起来似乎正常。
一般来说，推荐每页 5~10 篇文章最佳（即 per_page 为 5~10）。
