### ISSUE TITLE
[Feature] Custom CSS and JS files

### ISSUE THREAD

**Issue by zhonger** [zhonger/jekyll-theme-H2O-ac#27]
### Description

Sometimes users may want to customize some CSS style or JavaScript.
For example, a customized 404 page or font size of the top menu.

Until now, it can only be changed in the theme source files.
It should be defined by users according to their needs in the `config.yml` file or meta info in the page:

```yaml
----
css:
- https://example.com/custom.css
- https://example.com/custom2.css
js:
- https://example.com/custom.js
- https://example.com/custom2.js
----
```
